name: movirand
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  flutter_rating_bar: ^4.0.1 # https://pub.dev/packages/flutter_rating_bar
  loading_indicator: ^3.1.0 # https://pub.dev/packages/loading_indicator
  get: ^4.6.5 # https://pub.dev/packages/get
  get_storage: ^2.0.3 # https://pub.dev/packages/get_storage
  dot_navigation_bar: ^1.0.1+4 # https://pub.dev/packages/dot_navigation_bar
  glassmorphism: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # rules and activating additional ones.
  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true

